baseURL = 'https://yuki-portfolio-2025.netlify.app/'  # To change to new domain
languageCode = 'en-us'
title = 'Yukihide Takahashi'
theme = 'typo'

# Google analytics code
googleAnalytics = "G-VZMX4N5FX6"

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "Yukihide Takahashi's personal website"

showFooter = true
footerContent = "Thanks for visiting my page! and thanks [tomfran/typo](https://github.com/tomfran/typo) for the fantastic theme!"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi there!'
homeIntroContent = """
My name is Yukihide, and I'm a software engineer based in Tokyo, Japan.

I graduated from the National University of Singapore in 2024 with a B. Eng in Industrial Engineering.

I have a strong passion for AI and machine learning, both the theory and the applications.
In my current full-time role I am working on a semantic search feature for a hotel CMS.
My interests include LLMs, AI agents, information retrieval, and more.

Feel free to read [about me](/about) or to look at [my posts](/posts).

---

**Tech**: 

| Experience | Technology |
|------------|-------------|
| >= 1 year | {{< tech-tag name="Python" icon="python" >}} {{< tech-tag name="FastAPI" icon="fastapi" >}} {{< tech-tag name="Docker" icon="docker" >}} {{< tech-tag name="MySQL" icon="mysql" >}} {{< tech-tag name="AWS" icon="aws" >}} {{< tech-tag name="Bitbucket" icon="bitbucket" >}} {{< tech-tag name="Github" icon="github" >}} |
| 6 months ~ 1 year | {{< tech-tag name="Redis" icon="redis" >}} {{< tech-tag name="Pinecone" >}} {{< tech-tag name="Terraform" icon="terraform" >}} |
| ~ 6 months | {{< tech-tag name="C++" icon="cplusplus" >}} {{< tech-tag name="Java" icon="java" >}} {{< tech-tag name="MongoDB" icon="mongodb" >}} {{< tech-tag name="Gradio" >}} |



**Socials**: [Github](https://github.com/yuki-zmstr), [LinkedIn](https://www.linkedin.com/in/yukihide-takahashi/)
"""

# Collection to display on home
# homeCollectionTitle = 'Posts'
# homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
[params.breadcrumbs]
enabled = false
showCurrentPage = true
home = "Home"

# Social icons
# [[params.social]]
# name = "linkedin"
# url = "https://www.linkedin.com/in/yukihide-takahashi/"
# 
# [[params.social]]
# name = "github"
# url = "https://github.com/yuki-zmstr"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "about"
url = "/about"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "projects"
url = "/projects"


# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'colorful'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"
