baseURL = 'https://yuki-portfolio-2025.netlify.app/'  # To change to new domain
languageCode = 'en-us'
title = 'Yukihide Takahashi'
theme = 'typo'

# Google analytics code
googleAnalytics = "G-VZMX4N5FX6"

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "Yukihide Takahashi's personal website"

showFooter = true
footerContent = "Thanks for visiting my page! and thanks [tomfran/typo](https://github.com/tomfran/typo) for the fantastic theme!"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
# homeIntroTitle = 'Hi there.'
homeIntroContent = """

    "Always leave the campground cleaner than you found it."

[Reference](https://www.informit.com/articles/article.aspx?p=1235624&seqNum=6)

**Yukihide Takahashi** is a software engineer based in Tokyo, Japan who loves capybaras.

He graduated from the National University of Singapore in 2024 with a B. Eng in Industrial Engineering and a minor in Mathematics.

He has a strong passion for AI and machine learning, both the theory and the applications.
In his current full-time role he is working on a semantic search feature for a hotel CMS.
His interests include LLMs, AI agents, information retrieval, and more.

Feel free to read [about Yuki](/about) or to look at [his posts](/posts).

---

| Experience | Technology |
|------------|-------------|
| >= 1 year | {{< tech-tag name="Python" icon="python" url="https://docs.python.org/3/" >}} {{< tech-tag name="FastAPI" icon="fastapi" url="https://fastapi.tiangolo.com/" >}} {{< tech-tag name="Docker" icon="docker" url="https://docs.docker.com/" >}} {{< tech-tag name="MySQL" icon="mysql" url="https://dev.mysql.com/doc/" >}} {{< tech-tag name="AWS" icon="aws" url="https://docs.aws.amazon.com/" >}} {{< tech-tag name="Bitbucket" icon="bitbucket" url="https://bitbucket.org/" >}} {{< tech-tag name="Github" icon="github" url="https://github.com/" >}} |
| 6 months ~ 1 year | {{< tech-tag name="Redis" icon="redis" url="https://redis.io/docs/" >}} {{< tech-tag name="Flask" icon="flask" url="https://flask.palletsprojects.com/en/2.3.x/" >}} {{< tech-tag name="Terraform" icon="terraform" url="https://developer.hashicorp.com/terraform/docs" >}} {{< tech-tag name="Pinecone" url="https://docs.pinecone.io/" >}} {{< tech-tag name="FAISS" url="https://faiss.ai/index.html" >}}  |
| ~ 6 months | {{< tech-tag name="C++" icon="cplusplus" url="https://en.cppreference.com/w/" >}} {{< tech-tag name="Java" icon="java" url="https://docs.oracle.com/en/java/" >}} {{< tech-tag name="MongoDB" icon="mongodb" url="https://www.mongodb.com/docs/" >}} {{< tech-tag name="Gradio" url="https://www.gradio.app/docs/" >}} |

**Socials**: [Github](https://github.com/yuki-zmstr), [LinkedIn](https://www.linkedin.com/in/yukihide-takahashi/)

Last Updated: Sep 21 2025

"""

# Collection to display on home
# homeCollectionTitle = 'Posts'
# homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
[params.breadcrumbs]
enabled = false
showCurrentPage = true
home = "Home"

# Social icons
# [[params.social]]
# name = "linkedin"
# url = "https://www.linkedin.com/in/yukihide-takahashi/"
# 
# [[params.social]]
# name = "github"
# url = "https://github.com/yuki-zmstr"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "about"
url = "/about"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "projects"
url = "/projects"


# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'colorful'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"
